In [1]:
#pip install opencv-python

In [2]:
import numpy as np
import cv2 as cv

#### Reading & Displaying an Image

img1 = cv.imread('sbike.jpg')
cv.imshow('My First Image',img1)
cv.waitKey(0)
cv.destroyAllWindows()

In [3]:
img1 = cv.imread('sbike.jpg')
cv.imshow('My First Image',img1)
cv.waitKey(0)
cv.destroyAllWindows()

#### Playing a Video

In [4]:
vid1 = cv.VideoCapture('Flag.mp4')
while True:
    _ , frame = vid1.read()
    cv.imshow('My Video',frame)
    if cv.waitKey(20) & 0xFF==ord('q'):
        break
        
vid1.release()
cv.destroyAllWindows()

## Add shapes to an Image

### Circle

In [5]:
myimg = cv.imread('Golf img.jpg')
cv.circle(myimg, (220,330), 70, (155,255,228), thickness = 7)
cv.imshow('Image with Circle',myimg)
cv.waitKey(0)
cv.destroyAllWindows()

### Rectangle

In [6]:
myimg = cv.imread('Mouse.png')
cv.rectangle(myimg, (250,15), (15000,8000), (255,155,228), thickness = 10)
cv.imshow('Image with Rectangle',myimg)
cv.waitKey(0)
cv.destroyAllWindows()

## Face Detection in Images

In [7]:
img1= cv.imread('Face.jpg')
cv.imshow('Face Image', img1)
cv.waitKey()
cv.destroyAllWindows()

In [8]:
face_detect = cv.CascadeClassifier(cv.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [9]:
type(face_detect)

cv2.CascadeClassifier

In [22]:
face_detect.detectMultiScale(img1, scaleFactor=1.1, minNeighbors=5, minSize=(40,40))

array([[210,  86, 110, 110]])

In [23]:
face_grayscale = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
cv.imshow('Face.jpg',face_grayscale)
cv.waitKey(0)
cv.destroyAllWindows()

In [24]:
face_detect = cv.CascadeClassifier(cv.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [33]:
face_cords = face_detect.detectMultiScale(face_grayscale, scaleFactor = 1.1, minNeighbors = 5, minSize = (40,40))
face_cords

array([[210,  86, 110, 110]])

## Multiple Face Detection in Images

In [37]:
faces_1 = cv.imread('Faces1.jfif')
cv.imshow('Multiple Face Image', faces_1)
cv.waitKey(0)
cv.destroyAllWindows()

In [42]:
faces_1_grayscale = cv.cvtColor(faces_1, cv.COLOR_BGR2GRAY)
cv.imshow('image',faces_1_grayscale)
cv.waitKey(0)
cv.destroyAllWindows()

In [45]:
face_cords = face_detect.detectMultiScale(faces_1_grayscale, scaleFactor = 1.1, minNeighbors = 5, minSize = (40,40))

In [46]:
face_cords

array([[ 22,   9,  49,  49],
       [116,  12,  48,  48]])

In [49]:
for cords in face_cords:
    print((cords[0], cords[1]), (cords[0]+cords[2], cords[1]+cords[3]))

(22, 9) (71, 58)
(116, 12) (164, 60)


### Face Detection in WebCam Video

In [54]:
webcam = cv.VideoCapture(0)
cam_status, img = webcam.read()
print('Frame captured succesfully:', cam_status)
webcam.release()

Frame captured succesfully: True


In [56]:
face_detect = cv.CascadeClassifier(cv.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [58]:
def detect_faces():
    webcam = cv.VideoCapture(0)
    while True:
        _, frame = webcam.read()
        gray_frame = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
        faces = face_detect.detectMultiScale(gray_frame, scaleFactor=1.3, minNeighbors=5)
        
        for (x, y, w, h) in faces:
            cv.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
            cv.imshow('Face Detection', frame)
            if cv.waitKey(1) & 0xFF == ord('q'):
                break
    webcam.release()
    cv.destroyAllWindows()

In [59]:
detect_faces

<function __main__.detect_faces()>

In [60]:
webcam.release()